apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: xcndw2bxr-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: xcndw2bxr-go 
  name: xcndw2bxr-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: xcndw2bxr-go 
