apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: xcndw2bxr-go 
  janus-idp.io/tekton: xcndw2bxr-go
  backstage.io/kubernetes-id: xcndw2bxr-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: xcndw2bxr-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  